language: android
jdk: openjdk9
android:
  components:
    - build-tools-29.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - android-12
  licenses:
    - '.+'
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
