language: android
jdk: openjdk7
android:
  components:
    - build-tools-23.0.2
    - extra-android-m2repository
    - android-12
  licenses:
    - '.+'
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
