language: android
dist: trusty
jdk: openjdk9
android:
  components:
    - build-tools-29.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - android-12
  licenses:
    - '.+'
before_install:
 - yes | sdkmanager "build-tools;29.0.3"
 - yes | sdkmanager "platforms;android-29"
 - chmod +x gradlew
 - rm "${JAVA_HOME}/lib/security/cacerts"
 - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - ./gradlew check
